export const audioProducts = [
    {
        name: "Sony WH-1000XM5",
        description: "Industry-leading noise cancelling wireless headphones with 30-hour battery life.",
        image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb",
        specs: ["Active Noise Cancelling", "30hr Battery", "Hi-Res Audio", "Touch Controls"],
        amazonUrl: "https://amazon.com/dp/example1",
        reviewUrl: "#",
    },
    {
        name: "Bose SoundLink Speaker",
        description: "Portable Bluetooth speaker with 360-degree sound and 16-hour battery life.",
        image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1",
        specs: ["360° Sound", "16hr Battery", "Water Resistant", "Voice Assistant"],
        amazonUrl: "https://amazon.com/dp/example2",
        reviewUrl: "#",
    },
    {
        name: "Apple AirPods Pro",
        description: "Premium wireless earbuds with spatial audio and adaptive transparency.",
        image: "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1",
        specs: ["Spatial Audio", "ANC", "6hr + 24hr Case", "MagSafe Charging"],
        amazonUrl: "https://amazon.com/dp/example3",
        reviewUrl: "#",
    },
    {
        name: "JBL Soundbar",
        description: "Wireless soundbar with detachable surround speakers for immersive audio.",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64",
        specs: ["5.1 Surround", "Wireless Subwoofer", "4K HDR", "Chromecast Built-in"],
        amazonUrl: "https://amazon.com/dp/example4",
        reviewUrl: "#",
    },
    {
        name: "Gaming Headset",
        description: "Wireless gaming headset with lossless 2.4GHz connection and 24-hour battery.",
        image: "https://images.unsplash.com/photo-1599669454699-248893623440",
        specs: ["Wireless 2.4GHz", "24hr Battery", "DTS Headphone:X", "ClearCast Mic"],
        amazonUrl: "https://amazon.com/dp/example5",
        reviewUrl: "#",
    },
    {
        name: "Portable Bluetooth Speaker",
        description: "Hi-res Bluetooth speaker with customizable EQ and 12-hour playtime.",
        image: "https://images.unsplash.com/photo-1545454675-3531b543be5d",
        specs: ["Hi-Res Audio", "12hr Battery", "IPX7 Waterproof", "Custom EQ"],
        amazonUrl: "https://amazon.com/dp/example6",
        reviewUrl: "#",
    },
]