export const blogPosts = [
    {
        id: 20,
        slug: "remote-work-accessories-2025",
        title: "Remote Work Accessories 2025: Tools for a Smarter Home Office",
        excerpt:
            "Must-have home-office accessories to boost comfort and productivity—no prices shown on site.",
        category: "Guides",
        difficulty: "Beginner",
        tags: ["Smart Home", "USB-C"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-18",
        readMins: 9,
        image: "/images/blog/remote-work-accessories-2025/thumb.jpg", // optionnel
        alt: "Home office accessories on a desk",
    },

    {
        id: 19,
        slug: "ai-gadgets-2025",
        title: "AI Gadgets 2025: Smart Devices That Make Life Easier",
        excerpt:
            "Discover the smartest AI-powered devices of 2025 that make your daily routines faster, simpler, and more efficient.",
        category: "Reviews",
        difficulty: "Intermediate",
        tags: ["Smart Home", "Audio"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-18",
        readMins: 10,
        image: "/images/blog/ai-gadgets-2025/thumb.jpg",
        alt: "Collection of the best AI-powered gadgets for 2025 including smart assistants, wearables, and home devices",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 18,
        slug: "how-to-calibrate-4k-tv-2025",
        title: "How to Calibrate a 4K TV in 2025: Step-by-Step Guide for the Best Picture",
        excerpt:
            "Simple steps to unlock the full potential of your television with proper calibration for color accuracy, brightness, and overall viewing experience.",
        category: "How-tos",
        difficulty: "Intermediate",
        tags: ["Audio"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-17",
        readMins: 11,
        image: "/images/blog/how-to-calibrate-4k-tv-2025/thumb.jpg",
        alt: "Modern 4K TV in a living room showing calibration settings and tools for optimal picture quality",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 17,
        slug: "gaming-accessories-2025",
        title: "Gaming Accessories 2025: Gear That Levels Up Your Play",
        excerpt: "Discover the must-have accessories every gamer needs this year for better performance, comfort, and fun.",
        category: "Reviews",
        difficulty: "Beginner",
        tags: ["USB-C"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-16",
        readMins: 9,
        image: "/images/blog/gaming-accessories-2025/thumb.jpg",
        alt: "Collection of the best gaming accessories for 2025 including mouse, keyboard, headset, and controller",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 16,
        slug: "ultimate-2025-smartphone-buying-guide",
        title: "Ultimate 2025 Smartphone Buying Guide",
        excerpt:
            "Discover the top smartphones of 2025, compare specs, and find the perfect device for your budget and needs.",
        category: "Guides",
        difficulty: "Beginner",
        tags: ["Smart Home"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-15",
        readMins: 12,
        image: "/images/blog/ultimate-2025-smartphone-buying-guide/thumb.jpg",
        alt: "Collection of the best smartphones for 2025 including iPhone, Samsung, Google Pixel and gaming phones",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 15,
        slug: "best-power-banks-2025",
        title: "Best Power Banks 2025: Reliable Charging on the Go",
        excerpt:
            "Stay powered anywhere with the most reliable, fast-charging power banks of 2025. Compare capacity, speed, and portability.",
        category: "Reviews",
        difficulty: "Beginner",
        tags: ["USB-C"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-14",
        readMins: 8,
        image: "/images/blog/best-power-banks-2025/thumb.jpg",
        alt: "Collection of the best power banks for 2025 including portable and high-capacity models",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 14,
        slug: "mechanical-keyboards-2025",
        title: "Mechanical Keyboards 2025: Best Picks for Typing and Gaming",
        excerpt:
            "Discover the top mechanical keyboards of 2025 for work, study, and gaming. Compare switches, layouts, and value for money.",
        category: "Reviews",
        difficulty: "Intermediate",
        tags: ["USB-C"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-13",
        readMins: 10,
        image: "/images/blog/mechanical-keyboards-2025/thumb.jpg",
        alt: "Collection of the best mechanical keyboards for 2025 including gaming and productivity models",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 13,
        slug: "noise-cancelling-headphones-2025",
        title: "Noise-Cancelling Headphones 2025: Best Picks for Work and Travel",
        excerpt:
            "The ultimate guide to the best headphones for work, travel, and daily focus. Compare top models with detailed reviews and buying advice.",
        category: "Reviews",
        difficulty: "Beginner",
        tags: ["Audio"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-12",
        readMins: 9,
        image: "/images/blog/noise-cancelling-headphones-2025/thumb.jpg",
        alt: "Collection of the best noise-cancelling headphones for 2025 including premium and budget options",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 12,
        slug: "smart-home-gadgets-2025",
        title: "Smart Home Gadgets 2025: Must-Have Devices for a Connected Life",
        excerpt:
            "Transform your home into a smart sanctuary with cutting-edge devices that blend convenience, security, and energy efficiency.",
        category: "Guides",
        difficulty: "Intermediate",
        tags: ["Smart Home"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-05",
        readMins: 10,
        image: "/smart-home-devices-2025.jpg",
        alt: "Collection of smart home devices including smart displays, thermostats, and security cameras",
        published: true,
        featured: false,
        hidden: false,
    },
    {
        id: 11,
        slug: "usb-c-hubs-2025",
        title: "Best USB-C Hubs 2025: Top Picks for Every Budget",
        excerpt:
            "Compare affordable, mid-range, and premium USB-C hubs. Find the perfect hub for your devices with our detailed reviews and buying guide.",
        category: "Reviews",
        difficulty: "Beginner",
        tags: ["USB-C"],
        author: "AnadjyTech Editorial",
        publishedAt: "2025-09-09",
        readMins: 8,
        image: "/images/blog/usb-c-hubs-2025/thumb.jpg",
        alt: "Collection of the best USB-C hubs for 2025 including budget and premium options",
        published: true,
        featured: false,
        hidden: false,
    },
]