export const searchData = {
  products: [
    {
      id: 1,
      title: "iPhone 15 Pro Max",
      price: 1199,
      rating: 4.8,
      image: "/iphone-15-pro-max.png",
      category: "Smartphones",
      brand: "Apple",
      affiliate_url: "https://example.com/iphone-15-pro-max",
      keywords: ["smartphone", "mobile", "cell phone", "handset", "portable", "iphone", "apple"],
    },
    {
      id: 2,
      title: "MacBook Air M3",
      price: 1299,
      rating: 4.7,
      image: "/macbook-air-m3.png",
      category: "Laptops",
      brand: "Apple",
      affiliate_url: "https://example.com/macbook-air-m3",
      keywords: ["laptop", "notebook", "portable computer", "macbook", "apple", "m3"],
    },
    {
      id: 3,
      title: "AirPods Pro 2nd Gen",
      price: 249,
      rating: 4.6,
      image: "/airpods-pro-2.png",
      category: "Audio",
      brand: "Apple",
      affiliate_url: "https://example.com/airpods-pro-2",
      keywords: ["earbuds", "in-ear", "earphones", "true wireless", "tws", "airpods", "apple"],
    },
    {
      id: 4,
      title: "Samsung Galaxy S24 Ultra",
      price: 1299,
      rating: 4.7,
      image: "/samsung-s24-ultra.png",
      category: "Smartphones",
      brand: "Samsung",
      affiliate_url: "https://example.com/galaxy-s24-ultra",
      keywords: ["smartphone", "mobile", "cell phone", "galaxy", "samsung", "android"],
    },
    {
      id: 5,
      title: "Sony WH-1000XM5",
      price: 399,
      rating: 4.8,
      image: "/sony-wh-1000xm5.png",
      category: "Audio",
      brand: "Sony",
      affiliate_url: "https://example.com/sony-wh-1000xm5",
      keywords: ["headphones", "wireless", "noise-cancelling", "sony", "bluetooth"],
    },
    {
      id: 6,
      title: 'iPad Pro 12.9"',
      price: 1099,
      rating: 4.6,
      image: "/ipad-pro.png",
      category: "Tablets",
      brand: "Apple",
      affiliate_url: "https://example.com/ipad-pro",
      keywords: ["tablet", "ipad", "apple", "pro", "touchscreen"],
    },
  ],
  categories: [
    { name: "Smartphones", count: 45 },
    { name: "Laptops", count: 32 },
    { name: "Tablets", count: 18 },
    { name: "Audio", count: 67 },
    { name: "Smartwatches & Wearables", count: 23 },
    { name: "Gaming", count: 41 },
    { name: "Cameras & Photography", count: 29 },
    { name: "PC Accessories", count: 56 },
    { name: "Charging & Power", count: 34 },
    { name: "Home Tech", count: 38 },
  ],
  brands: [
    { name: "Apple" },
    { name: "Samsung" },
    { name: "Google" },
    { name: "Sony" },
    { name: "Microsoft" },
    { name: "Dell" },
    { name: "HP" },
    { name: "Lenovo" },
    { name: "Asus" },
    { name: "Bose" },
    { name: "JBL" },
    { name: "Anker" },
  ],
}